[colors.bright]
black = "0xb3b3b3"
blue = "0x5dc7ea"
cyan = "0x75a1a0"
green = "0xafdb80"
magenta = "0xd2a4b4"
red = "0xed5466"
white = "0x909090"
yellow = "0xf59335"

[colors.normal]
black = "0xd3d3d3"
blue = "0x4ec2e8"
cyan = "0x95c1c0"
green = "0xa1d569"
magenta = "0xfec7cd"
red = "0xef6b7b"
white = "0x707070"
yellow = "0xf59335"

[colors.primary]
background = "0xf3f3f3"
foreground = "0x707070"
