[colors.bright]
black = "0x76715e"
blue = "0x66d9ee"
cyan = "0x66efd5"
green = "0xa7e22e"
magenta = "0xae82ff"
red = "0xfa2772"
white = "0xcfd0c2"
yellow = "0xe7db75"

[colors.normal]
black = "0x48483e"
blue = "0x55bcce"
cyan = "0x56b7a5"
green = "0x8fc029"
magenta = "0x9358fe"
red = "0xdc2566"
white = "0xacada1"
yellow = "0xd4c96e"

[colors.primary]
background = "0x272822"
foreground = "0xf1ebeb"
