[colors.bright]
black = "0x065f73"
blue = "0x61778d"
cyan = "0x9ed9d8"
green = "0xa2d9b1"
magenta = "0xff99a1"
red = "0xef5847"
white = "0xf6f6c9"
yellow = "0xbeb090"

[colors.normal]
black = "0x032c36"
blue = "0x2e3340"
cyan = "0x44b5b1"
green = "0x7cbf9e"
magenta = "0xff5879"
red = "0xc2454e"
white = "0xf2f1b9"
yellow = "0x8a7a63"

[colors.primary]
background = "0x021b21"
foreground = "0xe8dfd6"
