[colors.bright]
black = "0x999999"
blue = "0x99ccff"
cyan = "0x99ffcc"
green = "0xccff99"
magenta = "0xcc99ff"
red = "0xff99cc"
white = "0xffffff"
yellow = "0xffcc99"

[colors.normal]
black = "0x666666"
blue = "0x6699cc"
cyan = "0x66cc99"
green = "0x99cc66"
magenta = "0x9966cc"
red = "0xcc6699"
white = "0xcccccc"
yellow = "0xcc9966"

[colors.primary]
background = "0x333333"
foreground = "0xcccccc"
