[colors.bright]
black = "0x7f7f7a"
blue = "0x5986b2"
cyan = "0xf2854a"
green = "0x664233"
magenta = "0xd9ae98"
red = "0xb23636"
white = "0x4c4742"
yellow = "0xbf8f60"

[colors.normal]
black = "0x666661"
blue = "0x4c7399"
cyan = "0xd97742"
green = "0x4c3226"
magenta = "0xbf9986"
red = "0x992e2e"
white = "0x34302d"
yellow = "0xa67c53"

[colors.primary]
background = "0xf5e7de"
foreground = "0x34302d"
