general {
    col.active_border = rgba(87929dAA)
    col.inactive_border = rgba(3d4852AA)
}

misc {
    background_color = rgba(0e1419FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(0e1419FF)
        col.text = rgba(dde3eaFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(dde3ea), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(dde3ea), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(dde3ea), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

# windowrulev2 = bordercolor rgba(d0ca69AA) rgba(d0ca6977),pinned:1
