require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.treesitter")
require("user.lsp")
require("user.null-ls")
require("user.autopairs")
require("user.cmp")
require("user.comment")
require("user.nvim-tree")
require("user.toggleterm")
require("user.bufferline")
require("user.lualine")

